@API_HostAddress = http://localhost:5000
@Host = localhost:5000

// User-Agent & Accept Fields Not Required? Research.

### SB-1
GET {{API_HostAddress}}/Sandbox/
Accept: application/json

### SB-2
GET {{API_HostAddress}}/Sandbox/MyEndpoint/
Accept: application/json

###								GET ALL REQUEST
GET /api/activities/ HTTP/1.1
Host: {{Host}}
User-Agent: insomnia/9.1.1
Accept: */*

###								GET SINGLE REQUEST
GET /api/activities/1b2fc87b-d6c3-414c-b6f9-221d274dc02c HTTP/1.1
Host: {{Host}}
User-Agent: insomnia/9.1.1
Accept: */*

###								POST CREATE REQUEST
POST /api/activities HTTP/1.1
Host: localhost:5000
Content-Type: application/json
User-Agent: insomnia/9.1.1
Accept: */*
Content-Length: 194

{
    "id": "{{$guid}}",
 	"title": "Past Activity",
 	"date": "{{$localDatetime iso8601 5 d}}",
 	"description": "Activity 2 days ago",
 	"category": "coding",
    "city": "Maldives",
	"venue": "OT Home"
}

###								PUT UPDATE REQUEST
PUT /api/activities/1b2fc87b-d6c3-414c-b6f9-221d274dc02c HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Content-Length: 214

{
	"title": "UPDATED 200",
	"description": "",
	"category": "Culture",
	"date": "{{$localDatetime iso8601 6 M}}",
	"city": "London",
	"venue": "Roundhouse Camden - CHANGED"
}