@API_HostAddress = http://localhost:5000
@Host = localhost:5000

// User-Agent & Accept Fields Not Required? Research.
// CANCEL REQUEST --> CTRL + ALT + k 

### SB-1
GET {{API_HostAddress}}/Sandbox/
Accept: application/json

### SB-2
GET {{API_HostAddress}}/Sandbox/MyEndpoint/
Accept: application/json

###
GET /api/activities/ HTTP/1.1
Host: {{Host}}
User-Agent: OT/4.2.1.6.9
Accept: */*

###								GET SINGLE REQUEST
GET /api/activities/212ea8da-a536-430c-991f-2fc516e2ac82 HTTP/1.1
Host: {{Host}}
Accept: */*

###								POST CREATE REQUEST
POST /api/activities HTTP/1.1
Host: localhost:5000
Content-Type: application/json
Accept: */*
Content-Length: 194

{
    "id": "{{$guid}}",
 	"title": "Past Activity",
 	"date": "{{$localDatetime iso8601 5 d}}",
 	"description": "Activity 2 days ago",
 	"category": "coding",
    "city": "Maldives",
	"venue": "OT Home"
}

###								PUT UPDATE REQUEST
PUT /api/activities/212ea8da-a536-430c-991f-2fc516e2ac82 HTTP/1.1
Host: {{Host}}
Content-Type: application/json

{
	"title": "Mapperly",
	// CHECK NULL WHEN REQUIRED
		// "date": "{{$localDatetime iso8601 6 M}}",
	// CHECK NULL
		// "description": "",
		// "category": "",
		// "city": "",
	// CHECK EMPTY
		"venue": ""
}

###								DELETE REQUEST
DELETE /api/activities/212ea8da-a536-430c-991f-2fc516e2ac82 HTTP/1.1
Host: {{Host}}
Accept: */*